### ISSUE TITLE
选择类型为all属性，重置后没返回空数组

### ISSUE THREAD

**Issue by GaryHjy** [FEMessage/el-select-area#10]
**Describe the bug**
设置type类型为all，触发重置操作之后，返回[{"":""},{"":""},{"":""}]

**Expected behavior**
重置之后应返回空数组[]

**environment information:**
 - Version 2.0.5

**Comment by lianghx-319** [comment]
- 这是向下兼容的结果，我也认为返回空数组比较合理
- 除了 type = “all”，其他 type 属性，当数据清空时也会返回一个空数组
- 现在是这样的
```js
type = "all" return [{"":""}, {"":""}, {"":""}]
type = "text" return ["", "", ""]
type = "code" return []
```
- BREAK CHANGE 后
```js
type = "all" return []
type = "text" return []
type = "code" return []
```
