### ISSUE TITLE
默认尺寸`size`应该和element保持一致，能支持全局尺寸定义

### ISSUE THREAD

**Issue by rexerwang** [FEMessage/el-select-area#55]
## Describe the bug
默认尺寸`size`应该和element保持一致，这样便于全局设置尺寸。

全局设置尺寸
```js
Vue.prototype.$ELEMENT = {size: 'mini'}
```

原el-select 组件默认尺寸，可支持全局size
> [el-select 源代码](https://github.com/ElemeFE/element/blob/2830c0478331543ff51951cad349d66170fd0120/packages/select/src/select.vue#L226)

```js
selectSize() {
      return this.size || this._elFormItemSize || (this.$ELEMENT || {}).size;
}
```

el-select-area 问题点
> [el-select-area 源代码](https://github.com/FEMessage/el-select-area/blob/4af32d5f74f3e8baa0bcede53c616ff0c0c47c56/src/el-select-area.vue#L98)
```js
    size: {
      type: String,
      default: 'medium', #不应该设置
      validator: val => ['small', 'medium', 'mini'].includes(val)
    },
```

可修改为：
```js
# 1.
    size: {
      type: String,
      validator: val => ['small', 'medium', 'mini'].includes(val)
    },

# 2.
    size: {
      type: String,
      default(){
        return (this.$ELEMENT || {}).size || 'medium' 
      },
      validator: val => ['small', 'medium', 'mini'].includes(val)
    },

```

## Expected behavior
能支持全局size设置

## environment information
 - Version: 2.1.0
 - OS: Ubuntu
 - Browser: chrome

**Comment by levy9527** [comment]
666，可以！

这个有历史原因，最初用户界面，觉得使用 medium 比较合适，就沿用至今了。

这个下周改了发版本
