### ISSUE TITLE
`auto-fill=false`时，结果未重置区域联级数据！！！

### ISSUE THREAD

**Issue by rexerwang** [FEMessage/el-select-area#58]
## Describe the bug
`auto-fill=false`时，未重置区域联级数据：
    省-市-县，更改省级选择时，未重置县级数据 

## Screenshots

第一次状态：
![image](https://user-images.githubusercontent.com/15629940/67076962-ca350d00-f1c0-11e9-822c-4333b7bba42e.png)
![image](https://user-images.githubusercontent.com/15629940/67077037-efc21680-f1c0-11e9-989d-f59e99677d62.png)

变更后：
![image](https://user-images.githubusercontent.com/15629940/67077070-02d4e680-f1c1-11e9-962b-7fb5b94a90ac.png)
![image](https://user-images.githubusercontent.com/15629940/67077082-0a948b00-f1c1-11e9-87eb-4ed760a3c439.png)

## To Reproduce
1. 先选择到县级，如：北京市-北京市-东城区
2. 更改省级数据：四川省
3. 就可以看到错误了

## Expected behavior
每次update时，正常重置下级联级数据

## environment information
 - Version [2.1.0]
 - OS: [Ubuntu]
 - Browser [Chrome]

**Comment by levy9527** [comment]
收到！
